config/routes.rb
Rails.application.routes.draw do
  resources :guestbooks
  get 'welcome/index'
  post 'welcome/sign'
  root 'welcome#index'

end

app/models/guestbook.rb
class Guestbook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  before_action :set_guestbook, only: [:show, :edit, :update, :destroy]

  # GET /guestbooks
  # GET /guestbooks.json
  def index
    @guestbooks = Guestbook.all
  end

  # GET /guestbooks/1
  # GET /guestbooks/1.json
  def show
  end

  # GET /guestbooks/new
  def new
    @guestbook = Guestbook.new
  end

  # GET /guestbooks/1/edit
  def edit
  end

  # POST /guestbooks
  # POST /guestbooks.json
  def create
    @guestbook = Guestbook.new(guestbook_params)

    respond_to do |format|
      if @guestbook.save
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully created.' }
        format.json { render :show, status: :created, location: @guestbook }
      else
        format.html { render :new }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guestbooks/1
  # PATCH/PUT /guestbooks/1.json
  def update
    respond_to do |format|
      if @guestbook.update(guestbook_params)
        format.html { redirect_to @guestbook, notice: 'Guestbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @guestbook }
      else
        format.html { render :edit }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbooks/1
  # DELETE /guestbooks/1.json
  def destroy
    @guestbook.destroy
    respond_to do |format|
      format.html { redirect_to guestbooks_url, notice: 'Guestbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guestbook
      @guestbook = Guestbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guestbook_params
      params.require(:guestbook).permit(:username, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @guestbook = Guestbook.all
    @new_guest = Guestbook.new
  end

  def sign
    guest = Guestbook.new(guestbook_params)
    if guest.valid?
      SaveGuestbookEntryJob
        .set(wait: 10.seconds)
        .perform_later(guestbook_params)

      redirect_to welcome_index_path
    else
      redirect_to welcome_index_path
    end
  end

  private

  def guestbook_params
    params.require(:guestbook).permit(:username, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/guestbooks/_form.html.erb
<%= form_for(@guestbook) do |f| %>
  <% if @guestbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guestbook.errors.count, "error") %> prohibited this guestbook from being saved:</h2>

      <ul>
      <% @guestbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guestbooks/edit.html.erb
<h1>Editing Guestbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @guestbook %> |
<%= link_to 'Back', guestbooks_path %>

app/views/guestbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guestbooks</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guestbooks.each do |guestbook| %>
      <tr>
        <td><%= guestbook.username %></td>
        <td><%= guestbook.body %></td>
        <td><%= link_to 'Show', guestbook %></td>
        <td><%= link_to 'Edit', edit_guestbook_path(guestbook) %></td>
        <td><%= link_to 'Destroy', guestbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guestbook', new_guestbook_path %>

app/views/guestbooks/new.html.erb
<h1>New Guestbook</h1>

<%= render 'form' %>

<%= link_to 'Back', guestbooks_path %>

app/views/guestbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @guestbook.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @guestbook.body %>
</p>

<%= link_to 'Edit', edit_guestbook_path(@guestbook) %> |
<%= link_to 'Back', guestbooks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hey there</h1>
<p>Sign my guestbook!</p>
<%= form_for @new_guest, url: {action: 'sign'} do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <%= f.submit 'Sign' %>
<% end %>
<ul>
  <% @guestbook.each do |guest| %>
    <li>
      <div>
        <h4><%= guest.username %></h4>
        <p><%= guest.body %></p>
        <p><%= guest.created_at %></p>
      </div>
    </li>
  <% end %>
</ul>